---
- name: tunnel create
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: create tunnel
      shell: ssh erdinc@192.168.77.131 -i /home/erdinc/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -vvv -o ProxyCommand="/usr/bin/nc -X 5 -x 127.0.0.1:1234 %h %p"
- name: test raw module
  hosts: all 
  tasks:
    - name: run ipconfig
      raw: ipconfig
      register: ipconfig
    - debug: var=ipconfig

- name: test stat module
  hosts: windows
  tasks:
    - name: test stat module on file
      win_stat: path="C:/Windows/win.ini"
      register: stat_file

    - debug: var=stat_file
