---
- name: tunnel create
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: create tunnel (2jh)
      shell: ssh -i $JH2_SSH_PRIVATE_KEY -W -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no -oProxyCommand="ssh -i $JH1_SSH_PRIVATE_KEY -W {{ jh2_ip }}:{{ jh2_ssh_port }} -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null {{ jh1_ssh_user }}@{{ jh1_ip }}" -fN -D  127.0.0.1:1234 -p {{ jh1_ssh_port }} {{ jh2_ssh_user }}@{{ jh2_ip }}
- name: test raw module
  hosts: windows 
  tasks:
    - name: run ipconfig
      raw: ipconfig
      register: ipconfig
    - debug: var=ipconfig

- name: test stat module
  hosts: windows
  tasks:
    - name: test stat module on file
      win_stat: path="C:/Windows/win.ini"
      register: stat_file

    - debug: var=stat_file
- name: tunnel destroy
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
    - name: create tunnel
      shell: ps axuf |grep 1234 | grep ssh |awk '{print $2}' |xargs kill -9
      ignore_errors: true
