---
- name: test raw module
  hosts: all 
  tasks:
    - name: Creating socks tunnel without passphrasecommand: bash -c 'autossh -M 0 -o ServerAliveInterval=30 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=no -o ControlPath=~/.ssh/cp/ssh-%r@%h:%p -CfNq -D 127.0.0.1:1234 -p {{ jh1_ssh_port }} -i ~/.ssh/cp/jumphost_keys/$JH1_SSH_PRIVATE_KEY -W {{ jh1_ssh_user }}@{{ jh1_ip }} -vvv;sleep 5'
      command: bash -c 'autossh -M 0 -o ServerAliveInterval=30 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/n
    - name: run ipconfig
      raw: ipconfig
      register: ipconfig
    - debug: var=ipconfig

- name: test stat module
  hosts: windows
  tasks:
    - name: test stat module on file
      win_stat: path="C:/Windows/win.ini"
      register: stat_file

    - debug: var=stat_file
