---
- name: tunnel create
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: create tunnel
      shell: ssh -i '{{ jh1_ssh_private_key }}' -fN -L 1234:localhost:{{ jh1_ssh_port }} {{ jh1_ssh_user }}@{{ jh1_ip }}
- name: test raw module
  hosts: all 
  tasks:
    - name: run ipconfig
      raw: ipconfig
      register: ipconfig
    - debug: var=ipconfig

- name: test stat module
  hosts: windows
  tasks:
    - name: test stat module on file
      win_stat: path="C:/Windows/win.ini"
      register: stat_file

    - debug: var=stat_file
